const projects = [
    {
        name: 'Rocketeer Helmets',
        detail: 'HTML, CSS e Responsividade.',
        complete: false, landing: true, game: false,
        src: './assets/mockups/rockteer-helmets-img.jpg',
        href: 'https://github.com/feliperyo/rocketeer-helmets',
    },
    {
        name: 'Barber Shop',
        detail: 'HTML, CSS e Responsividade.',
        complete: false, landing: true, game: false,
        src: './assets/mockups/barber-shop-img.jpg',
        href: 'https://github.com/feliperyo/barber-shop',
    },
    {
        name: 'Mario Brothers',
        detail: 'HTML, CSS, JavaScript e Responsividade.',
        complete: true, landing: false, game: false,
        src: './assets/mockups/mario-img.jpg',
        href: 'https://github.com/feliperyo/mario-brothers',
    },
    {
        name: 'Coffee Page',
        detail: 'HTML, CSS e Responsividade.',
        complete: true, landing: false, game: false,
        src: './assets/mockups/coffee-img.jpg',
        href: 'https://github.com/feliperyo/coffee-page',
    },
    {
        name: 'Ibliz Inc Pumpkin',
        detail: 'HTML, CSS e Responsividade.',
        complete: false, landing: true, game: false,
        src: './assets/mockups/ibliz-pumpkin-img.jpg',
        href: 'https://github.com/feliperyo/ibliz-inc-pumpkin',
    },
    {
        name: 'Ibliz Inc Ghosts',
        detail: 'HTML, CSS e Responsividade.',
        complete: false, landing: true, game: false,
        src: './assets/mockups/ghosts-img.jpg',
        href: 'https://github.com/feliperyo/ibliz-inc-ghosts',
    },
    {
        name: 'X-Lanches',
        detail: 'HTML, CSS, JavaScript e Responsividade.',
        complete: true, landing: false, game: false,
        src: './assets/mockups/x-lanches-img.jpg',
        href: 'https://github.com/feliperyo/x-lanches',
    },
    {
        name: 'Conversor de Moedas',
        detail: 'HTML, CSS, JavaScript e Responsividade.',
        complete: true, landing: false, game: true,
        src: './assets/mockups/conversor-img.jpg',
        href: 'https://github.com/feliperyo/currency-converter',
    },
    {
        name: 'Eye.z Login',
        detail: 'HTML, CSS, JavaScript e Responsividade (Mobile First).',
        complete: false, landing: false, game: true,
        src: './assets/mockups/eye-z-img.jpg',
        href: 'https://github.com/feliperyo/eye-z',
    },
    {
        name: 'Starbucks',
        detail: 'HTML, CSS, JavaScript e Responsividade.',
        complete: false, landing: true, game: true,
        src: './assets/mockups/starbucks-img.jpg',
        href: 'https://github.com/feliperyo/starbucks',
    },
    {
        name: 'Previsão do Tempo',
        detail: 'HTML, CSS, JavaScript, Consumo de API e Responsividade.',
        complete: true, landing: false, game: true,
        src: './assets/mockups/tempo-img.jpg',
        href: 'https://github.com/feliperyo/weather-forecast',
    },
    {
        name: 'Jogo de Adivinhação',
        detail: 'HTML, CSS, JavaScript e Responsividade.',
        complete: true, landing: false, game: true,
        src: './assets/mockups/divination-game-img.jpg',
        href: 'https://github.com/feliperyo/divination-game',
    },
    {
        name: 'Sorteio de Número',
        detail: 'HTML, CSS, JavaScript e Responsividade.',
        complete: true, landing: false, game: true,
        src: './assets/mockups/sort-number-img.jpg',
        href: 'https://github.com/feliperyo/sorteio-de-numero',
    },
    {
        name: 'Joken-Pô',
        detail: 'HTML, CSS, JavaScript e Responsividade.',
        complete: true, landing: false, game: true,
        src: './assets/mockups/joken-po-img.jpg',
        href: 'https://github.com/feliperyo/joken-po',
    },
    {
        name: 'Calculadora',
        detail: 'HTML, CSS, JavaScript e Responsividade.',
        complete: true, landing: false, game: true,
        src: './assets/mockups/calculator-img.jpg',
        href: 'https://github.com/feliperyo/calculadora',
    },
    {
        name: 'Cronômetro',
        detail: 'HTML, CSS, JavaScript e Responsividade.',
        complete: true, landing: false, game: true,
        src: './assets/mockups/cronometro-img.jpg',
        href: 'https://github.com/feliperyo/cronometro',
    },
    {
        name: 'Pet',
        detail: 'HTML, CSS e Responsividade.',
        complete: false, landing: true, game: false,
        src: './assets/mockups/pet-img.jpg',
        href: 'https://github.com/feliperyo/cuidamos-do-seu-pet',
    },
    {
        name: 'Via Móvel',
        detail: 'HTML, CSS e Responsividade.',
        complete: false, landing: true, game: false,
        src: './assets/mockups/via-movel-img.jpg',
        href: 'https://github.com/feliperyo/via-movel',
    },
    {
        name: 'Ampla Cobertura',
        detail: 'HTML, CSS e Responsividade.',
        complete: false, landing: true, game: false,
        src: './assets/mockups/ampla-cobertura-img.jpg',
        href: 'https://github.com/feliperyo/ampla-cobertura',
    }
]